FROM nginx:alpine

# Copy static files
COPY ai-cost-calculator.html /usr/share/nginx/html/calculator/index.html
COPY ai-calculator-methodology.html /usr/share/nginx/html/calculator/methodology/index.html
COPY landingpage.html /usr/share/nginx/html/index.html
COPY logo.png /usr/share/nginx/html/logo.png
COPY dw-analytics.js /usr/share/nginx/html/dw-analytics.js

# Programmatic SEO landing pages (generated by seo/build-*.mjs)
COPY roles/ /usr/share/nginx/html/roles/
COPY insights/ /usr/share/nginx/html/insights/
COPY frameworks/ /usr/share/nginx/html/frameworks/
COPY advisory/ /usr/share/nginx/html/advisory/
COPY data/ /usr/share/nginx/html/data/
COPY sitemap.xml /usr/share/nginx/html/sitemap.xml
COPY robots.txt /usr/share/nginx/html/robots.txt
COPY llms.txt /usr/share/nginx/html/llms.txt

# Copy nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Cloud Run requires port 8080
EXPOSE 8080
